package com.hireai.resume.service.impl;

import com.hireai.application.repository.ApplicationRepository;
import com.hireai.resume.dto.response.ResumeResponse;
import com.hireai.resume.entity.Resume;
import com.hireai.resume.repository.ResumeRepository;
import com.hireai.resume.service.ResumeService;
import com.hireai.user.entity.User;
import com.hireai.user.enums.Role;
import com.hireai.user.repository.UserRepository;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;

import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.beans.factory.annotation.Value;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.List;
import java.util.UUID;

@Service
public class ResumeServiceImpl implements ResumeService {

    @Value("${hireai.upload.resume-dir:uploads/resumes}")
    private String uploadDir;
    private static final String PDF_CONTENT_TYPE = "application/pdf";

    /*
     * Keep this aligned with the file-upload limit configured
     * elsewhere in the application if one already exists.
     */
    private static final long MAX_FILE_SIZE = 5 * 1024 * 1024;

    private final ResumeRepository resumeRepository;
    private final UserRepository userRepository;
    private final ApplicationRepository applicationRepository;

    public ResumeServiceImpl(
            ResumeRepository resumeRepository,
            UserRepository userRepository,
            ApplicationRepository applicationRepository
    ) {
        this.resumeRepository = resumeRepository;
        this.userRepository = userRepository;
        this.applicationRepository = applicationRepository;
    }

    // =========================================================
    // CANDIDATE - UPLOAD RESUME
    // POST /api/v1/resumes
    // =========================================================

    @Override
    @Transactional
    public ResumeResponse uploadResume(
            MultipartFile file,
            String email
    ) {

        validateFile(file);

        User candidate = findCandidateByEmail(email);

        Path uploadPath = getUploadPath();

        Path newFilePath = null;

        try {

            Files.createDirectories(uploadPath);

            /*
             * Preserve the original filename only for display.
             * The physical filename is always generated by the
             * server to prevent path traversal and filename collisions.
             */
            String originalFileName = sanitizeOriginalFileName(
                    file.getOriginalFilename()
            );

            String storedFileName =
                    UUID.randomUUID() + "_resume.pdf";

            newFilePath = uploadPath
                    .resolve(storedFileName)
                    .normalize();

            ensurePathInsideUploadDirectory(
                    newFilePath,
                    uploadPath
            );

            /*
             * Save the uploaded PDF physically first.
             */
            Files.copy(
                    file.getInputStream(),
                    newFilePath,
                    StandardCopyOption.REPLACE_EXISTING
            );

            /*
             * =====================================================
             * EXTRACT TEXT FROM PDF
             * =====================================================
             *
             * PDFBox 3.x uses Loader.loadPDF().
             *
             * The extracted text is required later by:
             * JobMatchServiceImpl
             * ResumeAnalysisServiceImpl
             */
            String extractedText = extractTextFromPdf(newFilePath);

            /*
             * Make sure the PDF actually contains extractable text.
             *
             * A scanned/image-only PDF may technically be a valid PDF
             * but contain no machine-readable text.
             */
            if (extractedText == null || extractedText.isBlank()) {

                deleteUploadedFileAfterFailure(newFilePath);

                throw new IllegalArgumentException(
                        "Unable to extract text from the resume PDF. "
                                + "Please upload a text-based PDF."
                );
            }

            String newFileUrl =
                    "/uploads/resumes/" + storedFileName;

            /*
             * Find the current/latest resume.
             */
            Resume oldResume =
                    resumeRepository
                            .findTopByCandidateOrderByUploadedAtDesc(
                                    candidate
                            )
                            .orElse(null);

            /*
             * Build the new Resume entity.
             *
             * IMPORTANT:
             * extractedText is now stored here.
             */
            Resume resume = Resume.builder()
                    .candidate(candidate)
                    .fileName(originalFileName)
                    .fileUrl(newFileUrl)
                    .contentType(PDF_CONTENT_TYPE)
                    .fileSize(file.getSize())
                    .extractedText(extractedText)
                    .build();

            Resume savedResume =
                    resumeRepository.save(resume);

            /*
             * Keep the user's profile resume URL synchronized.
             */
            candidate.setResumeUrl(newFileUrl);
            userRepository.save(candidate);

            /*
             * Delete the old physical file and database record
             * only after the new resume has been persisted.
             */
            if (oldResume != null
                    && !oldResume.getId().equals(savedResume.getId())) {

                deletePhysicalFile(
                        oldResume.getFileUrl(),
                        uploadPath
                );

                resumeRepository.delete(oldResume);
            }

            return mapToResponse(savedResume);

        } catch (IOException ex) {

            /*
             * If PDF saving or PDF extraction fails,
             * remove the newly uploaded physical file.
             */
            if (newFilePath != null) {
                deleteUploadedFileAfterFailure(newFilePath);
            }

            throw new IllegalStateException(
                    "Failed to upload or process resume PDF.",
                    ex
            );

        } catch (RuntimeException ex) {

            /*
             * If extraction or another runtime operation fails
             * before the database transaction is successfully
             * completed, remove the newly uploaded physical file.
             */
            if (newFilePath != null) {
                deleteUploadedFileAfterFailure(newFilePath);
            }

            throw ex;
        }
    }

    // =========================================================
    // EXTRACT TEXT FROM PDF
    // =========================================================

    private String extractTextFromPdf(
            Path pdfPath
    ) throws IOException {

        if (pdfPath == null) {
            throw new IllegalArgumentException(
                    "PDF file path is required."
            );
        }

        if (!Files.exists(pdfPath)
                || !Files.isRegularFile(pdfPath)) {

            throw new IllegalArgumentException(
                    "Uploaded PDF file could not be found."
            );
        }

        /*
         * PDFBox 3.x:
         *
         * Loader.loadPDF(...)
         *
         * loads the PDF document.
         */
        try (PDDocument document =
                     Loader.loadPDF(pdfPath.toFile())) {

            PDFTextStripper pdfTextStripper =
                    new PDFTextStripper();

            /*
             * Extract text from all pages.
             */
            String extractedText =
                    pdfTextStripper.getText(document);

            if (extractedText == null) {
                return null;
            }

            /*
             * Normalize excessive blank lines and whitespace
             * while preserving useful resume content.
             */
            return extractedText
                    .replace("\r\n", "\n")
                    .replace("\r", "\n")
                    .replaceAll("[ \\t]+", " ")
                    .replaceAll("\n{3,}", "\n\n")
                    .trim();
        }
    }

    // =========================================================
    // DELETE NEWLY UPLOADED FILE AFTER FAILURE
    // =========================================================

    private void deleteUploadedFileAfterFailure(
            Path filePath
    ) {

        if (filePath == null) {
            return;
        }

        try {

            Files.deleteIfExists(filePath);

        } catch (IOException ignored) {

            /*
             * Do not hide the original upload/extraction exception
             * if cleanup itself fails.
             */
        }
    }

    // =========================================================
    // CANDIDATE - GET MY RESUMES
    // GET /api/v1/resumes/my
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public List<ResumeResponse> getMyResumes(
            String email
    ) {

        User candidate = findCandidateByEmail(email);

        return resumeRepository
                .findByCandidate(candidate)
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    // =========================================================
    // CANDIDATE - GET RESUME BY ID
    // GET /api/v1/resumes/{id}
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public ResumeResponse getResumeById(
            Long id,
            String email
    ) {

        validateId(id, "Resume ID");

        User candidate = findCandidateByEmail(email);

        /*
         * Ownership is enforced directly by the repository query.
         */
        Resume resume = resumeRepository
                .findByIdAndCandidate(id, candidate)
                .orElseThrow(() ->
                        new IllegalArgumentException(
                                "Resume not found."
                        )
                );

        return mapToResponse(resume);
    }

    // =========================================================
    // CANDIDATE - DELETE RESUME
    // DELETE /api/v1/resumes/{id}
    // =========================================================

    @Override
    @Transactional
    public void deleteResume(
            Long id,
            String email
    ) {

        validateId(id, "Resume ID");

        User candidate = findCandidateByEmail(email);

        /*
         * Ownership is enforced by the repository query.
         */
        Resume resume = resumeRepository
                .findByIdAndCandidate(id, candidate)
                .orElseThrow(() ->
                        new IllegalArgumentException(
                                "Resume not found."
                        )
                );

        String fileUrl = resume.getFileUrl();

        Path uploadPath = getUploadPath();

        /*
         * Delete physical file.
         */
        deletePhysicalFile(
                fileUrl,
                uploadPath
        );

        /*
         * Delete database record.
         */
        resumeRepository.delete(resume);

        /*
         * Clear the user's resumeUrl only if this was
         * the resume currently referenced by the profile.
         */
        if (fileUrl != null
                && fileUrl.equals(candidate.getResumeUrl())) {

            candidate.setResumeUrl(null);
            userRepository.save(candidate);
        }
    }

    // =========================================================
    // HR - GET CANDIDATE RESUME
    // GET /api/v1/resumes/candidate/{candidateId}
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public ResumeResponse getCandidateResume(
            Long candidateId,
            String hrEmail
    ) {

        validateId(candidateId, "Candidate ID");

        /*
         * Find and validate the authenticated HR.
         */
        User hr = findHrByEmail(hrEmail);

        /*
         * Find and validate the target candidate.
         */
        User candidate = findCandidateById(candidateId);

        /*
         * IMPORTANT SECURITY CHECK:
         *
         * The HR may access the candidate's resume only when
         * that candidate has applied to at least one job owned
         * by this HR.
         *
         * This prevents an HR from requesting arbitrary
         * candidate resumes by changing candidateId.
         */
        verifyHrCandidateAccess(
                candidate,
                hr
        );

        Resume latestResume =
                resumeRepository
                        .findTopByCandidateOrderByUploadedAtDesc(
                                candidate
                        )
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Candidate has not uploaded a resume."
                                )
                        );

        return mapToResponse(latestResume);
    }

    // =========================================================
    // HR - DOWNLOAD CANDIDATE RESUME
    // GET /api/v1/resumes/candidate/{candidateId}/download
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public ResponseEntity<Resource> downloadCandidateResume(
            Long candidateId,
            String hrEmail
    ) {

        validateId(candidateId, "Candidate ID");

        /*
         * Find and validate the authenticated HR.
         */
        User hr = findHrByEmail(hrEmail);

        /*
         * Find and validate the target candidate.
         */
        User candidate = findCandidateById(candidateId);

        /*
         * IMPORTANT SECURITY CHECK:
         *
         * The HR may download the candidate's resume only when
         * that candidate has applied to at least one job owned
         * by this HR.
         */
        verifyHrCandidateAccess(
                candidate,
                hr
        );

        Resume resume =
                resumeRepository
                        .findTopByCandidateOrderByUploadedAtDesc(
                                candidate
                        )
                        .orElseThrow(() ->
                                new IllegalArgumentException(
                                        "Candidate has not uploaded a resume."
                                )
                        );

        return buildResumeResponse(
                resume,
                false
        );
    }

    // =========================================================
    // HR - VERIFY CANDIDATE ACCESS
    // =========================================================

    /**
     * Verifies that the specified HR has a legitimate
     * application relationship with the candidate.
     *
     * The candidate must have applied to at least one job
     * owned by this HR.
     *
     * This protects the HR resume endpoints against
     * unauthorized candidateId enumeration / IDOR access.
     */
    private void verifyHrCandidateAccess(
            User candidate,
            User hr
    ) {

        if (candidate == null) {
            throw new IllegalArgumentException(
                    "Candidate is required."
            );
        }

        if (hr == null) {
            throw new IllegalArgumentException(
                    "HR is required."
            );
        }

        boolean authorized =
                applicationRepository
                        .existsByCandidateAndJob_Hr(
                                candidate,
                                hr
                        );

        if (!authorized) {
            throw new AccessDeniedException(
                    "You are not authorized to access this candidate's resume."
            );
        }
    }

    // =========================================================
    // CANDIDATE - VIEW RESUME PDF
    // GET /api/v1/resumes/{id}/view
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public ResponseEntity<Resource> viewResume(
            Long id,
            String email
    ) {

        validateId(id, "Resume ID");

        User candidate = findCandidateByEmail(email);

        /*
         * Ownership is enforced directly by the repository.
         */
        Resume resume = resumeRepository
                .findByIdAndCandidate(id, candidate)
                .orElseThrow(() ->
                        new IllegalArgumentException(
                                "Resume not found."
                        )
                );

        return buildResumeResponse(
                resume,
                true
        );
    }

    // =========================================================
    // FIND CANDIDATE BY EMAIL
    // =========================================================

    private User findCandidateByEmail(
            String email
    ) {

        String normalizedEmail =
                normalizeEmail(email);

        User user = userRepository
                .findByEmail(normalizedEmail)
                .orElseThrow(() ->
                        new IllegalArgumentException(
                                "Candidate not found."
                        )
                );

        if (user.getRole() != Role.CANDIDATE) {
            throw new IllegalArgumentException(
                    "Only candidates can access resumes."
            );
        }

        return user;
    }

    // =========================================================
    // FIND HR BY EMAIL
    // =========================================================

    private User findHrByEmail(
            String email
    ) {

        String normalizedEmail =
                normalizeEmail(email);

        User hr = userRepository
                .findByEmail(normalizedEmail)
                .orElseThrow(() ->
                        new IllegalArgumentException(
                                "HR not found."
                        )
                );

        if (hr.getRole() != Role.HR) {
            throw new IllegalArgumentException(
                    "Only HR can access candidate resumes."
            );
        }

        return hr;
    }

    // =========================================================
    // FIND CANDIDATE BY ID
    // =========================================================

    private User findCandidateById(
            Long candidateId
    ) {

        User candidate = userRepository
                .findById(candidateId)
                .orElseThrow(() ->
                        new IllegalArgumentException(
                                "Candidate not found."
                        )
                );

        if (candidate.getRole() != Role.CANDIDATE) {
            throw new IllegalArgumentException(
                    "The specified user is not a candidate."
            );
        }

        return candidate;
    }

    // =========================================================
    // VALIDATE UPLOAD FILE
    // =========================================================

    private void validateFile(
            MultipartFile file
    ) {

        if (file == null || file.isEmpty()) {
            throw new IllegalArgumentException(
                    "Resume file is required."
            );
        }

        if (file.getSize() > MAX_FILE_SIZE) {
            throw new IllegalArgumentException(
                    "Resume file must not exceed 5 MB."
            );
        }

        String contentType =
                file.getContentType();

        if (!PDF_CONTENT_TYPE.equalsIgnoreCase(contentType)) {
            throw new IllegalArgumentException(
                    "Only PDF files are allowed."
            );
        }

        String originalFileName =
                file.getOriginalFilename();

        if (originalFileName == null
                || originalFileName.isBlank()) {

            throw new IllegalArgumentException(
                    "Resume file name is required."
            );
        }

        String normalizedName =
                originalFileName
                        .trim()
                        .toLowerCase();

        if (!normalizedName.endsWith(".pdf")) {
            throw new IllegalArgumentException(
                    "Resume file must have a .pdf extension."
            );
        }
    }

    // =========================================================
    // SANITIZE ORIGINAL FILE NAME
    // =========================================================

    private String sanitizeOriginalFileName(
            String originalFileName
    ) {

        if (originalFileName == null
                || originalFileName.isBlank()) {

            return "resume.pdf";
        }

        String fileName =
                Paths.get(originalFileName)
                        .getFileName()
                        .toString()
                        .trim();

        if (fileName.isBlank()) {
            return "resume.pdf";
        }

        return fileName;
    }

    // =========================================================
    // BUILD FILE RESPONSE
    // =========================================================

    private ResponseEntity<Resource> buildResumeResponse(
            Resume resume,
            boolean inline
    ) {

        if (resume == null) {
            throw new IllegalArgumentException(
                    "Resume is required."
            );
        }

        String fileUrl =
                resume.getFileUrl();

        if (fileUrl == null
                || fileUrl.isBlank()) {

            throw new IllegalStateException(
                    "Resume file URL is missing."
            );
        }

        Path uploadPath =
                getUploadPath();

        String storedFileName =
                Paths.get(fileUrl)
                        .getFileName()
                        .toString();

        if (storedFileName.isBlank()) {
            throw new IllegalStateException(
                    "Resume file name is invalid."
            );
        }

        Path filePath =
                uploadPath
                        .resolve(storedFileName)
                        .normalize();

        ensurePathInsideUploadDirectory(
                filePath,
                uploadPath
        );

        Resource resource =
                new FileSystemResource(filePath);

        if (!resource.exists()
                || !resource.isReadable()) {

            throw new IllegalStateException(
                    "Resume file not found."
            );
        }

        String disposition =
                inline
                        ? "inline"
                        : "attachment";

        String displayFileName =
                sanitizeOriginalFileName(
                        resume.getFileName()
                );

        return ResponseEntity
                .ok()
                .contentType(
                        MediaType.APPLICATION_PDF
                )
                .header(
                        HttpHeaders.CONTENT_DISPOSITION,
                        disposition
                                + "; filename=\""
                                + displayFileName
                                + "\""
                )
                .body(resource);
    }

    // =========================================================
    // DELETE PHYSICAL FILE
    // =========================================================

    private void deletePhysicalFile(
            String fileUrl,
            Path uploadPath
    ) {

        if (fileUrl == null
                || fileUrl.isBlank()) {

            return;
        }

        try {

            String storedFileName =
                    Paths.get(fileUrl)
                            .getFileName()
                            .toString();

            if (storedFileName.isBlank()) {
                throw new IllegalStateException(
                        "Resume file name is invalid."
                );
            }

            Path filePath =
                    uploadPath
                            .resolve(storedFileName)
                            .normalize();

            ensurePathInsideUploadDirectory(
                    filePath,
                    uploadPath
            );

            Files.deleteIfExists(filePath);

        } catch (IOException ex) {

            throw new IllegalStateException(
                    "Failed to delete resume file.",
                    ex
            );
        }
    }

    // =========================================================
// GET UPLOAD PATH
// =========================================================

    private Path getUploadPath() {

        String configuredUploadDir = uploadDir;

        if (configuredUploadDir == null || configuredUploadDir.isBlank()) {
            configuredUploadDir = "uploads/resumes";
        }

        return Paths
                .get(configuredUploadDir)
                .toAbsolutePath()
                .normalize();
    }

    // =========================================================
    // PATH SECURITY
    // =========================================================

    private void ensurePathInsideUploadDirectory(
            Path filePath,
            Path uploadPath
    ) {

        Path normalizedFilePath =
                filePath
                        .toAbsolutePath()
                        .normalize();

        Path normalizedUploadPath =
                uploadPath
                        .toAbsolutePath()
                        .normalize();

        if (!normalizedFilePath.startsWith(
                normalizedUploadPath
        )) {

            throw new IllegalStateException(
                    "Invalid resume file path."
            );
        }
    }

    // =========================================================
    // NORMALIZE EMAIL
    // =========================================================

    private String normalizeEmail(
            String email
    ) {

        if (email == null
                || email.isBlank()) {

            throw new IllegalArgumentException(
                    "User email is required."
            );
        }

        return email
                .trim()
                .toLowerCase();
    }

    // =========================================================
    // VALIDATE ID
    // =========================================================

    private void validateId(
            Long id,
            String fieldName
    ) {

        if (id == null || id <= 0) {

            throw new IllegalArgumentException(
                    fieldName
                            + " must be greater than 0."
            );
        }
    }

    // =========================================================
    // ENTITY -> RESPONSE DTO
    // =========================================================

    private ResumeResponse mapToResponse(
            Resume resume
    ) {

        if (resume == null) {
            throw new IllegalArgumentException(
                    "Resume is required."
            );
        }

        User candidate =
                resume.getCandidate();

        return ResumeResponse.builder()
                .id(resume.getId())
                .fileName(resume.getFileName())
                .fileUrl(resume.getFileUrl())
                .contentType(resume.getContentType())
                .fileSize(resume.getFileSize())
                .uploadedAt(resume.getUploadedAt())
                .candidateId(
                        candidate != null
                                ? candidate.getId()
                                : null
                )
                .candidateName(
                        buildCandidateName(candidate)
                )
                .candidateEmail(
                        candidate != null
                                ? candidate.getEmail()
                                : null
                )
                .resumeUrl(
                        candidate != null
                                ? candidate.getResumeUrl()
                                : null
                )
                .build();
    }

    // =========================================================
    // BUILD CANDIDATE NAME
    // =========================================================

    private String buildCandidateName(
            User candidate
    ) {

        if (candidate == null) {
            return null;
        }

        String firstName =
                candidate.getFirstName();

        String lastName =
                candidate.getLastName();

        if (firstName == null
                && lastName == null) {

            return null;
        }

        if (firstName == null
                || firstName.isBlank()) {

            return lastName;
        }

        if (lastName == null
                || lastName.isBlank()) {

            return firstName;
        }

        return firstName.trim()
                + " "
                + lastName.trim();
    }
}